### ISSUE TITLE
incomplete package when using "sudo apt-get install ros-indigo-camera1394stereo"  

### ISSUE THREAD

**Issue by jeremy-a** [srv/camera1394stereo#4]
See this ros.answers.org question (http://answers.ros.org/question/218569/camera1394stereo-missing-nodes-on-indigo/).

Essentially it seems that the install is not configured in the `CMakeLists.txt` for this package. Therefore, using `sudo apt-get install ros-indigo-camera1394stereo` delivers an incomplete package.

**Comment by miquelmassot** [comment]
Hi @jeremy-a-asi! Thanks for reporting. I'll try to fix the installation targets for this package to work. Please hold on.

**Comment by miquelmassot** [comment]
Fixed with ros/rosdistro#9676
